#!/bin/sh

status="$(cat /sys/class/power_supply/AC/online)"
battery="$(cat /sys/class/power_supply/BAT0/capacity)"

if [ "${status}" -eq 1 ]; then
	printf "🔌"
else
	case $battery in
	100 | 9[0-9] | 8[3-9]) printf " " ;;
	8[0-2] | 7[0-9] | 6[6-9]) printf " " ;;
	6[0-5] | 5[0-9] | 49) printf " " ;;
	4[0-8] | 3[2-9]) printf " " ;;
	3[0-1] | 2[0-9] | 1[5-9]) printf " " ;;
	*) printf " " ;;
	esac
fi

printf " %s%%\n" "$battery"
