#!/bin/sh

# Sends a notification notifying you about the
# amount of packages needed to be updated

updates_arch=$(checkupdates 2> /dev/null | wc -l ) || updates_arch=0
updates_aur=$(yay -Qum 2> /dev/null | wc -l) || updates_aur=0
echo $(($updates_arch + $updates_aur))

