#!/usr/bin/env bash
#MISE description="Format shell scripts"
set -euo pipefail

git ls-files --cached --others --exclude-standard -z |
  while IFS= read -r -d '' file; do
    [[ -f $file && ! -L $file ]] || continue

    first_line=$(head -n 1 "$file")
    [[ $first_line == '#!'* ]] || continue

    interpreter=${first_line#\#!}
    interpreter=${interpreter##*env }
    interpreter=${interpreter#-S }
    interpreter=${interpreter##*/}
    interpreter=${interpreter%% *}

    case $interpreter in
    ash | bash | dash | ksh | mksh | sh | yash | zsh)
      shfmt -w -i 2 -s "$file"
      ;;
    esac
  done
