#!/bin/bash

if [ "$1" = "--status" ]; then
    mapfile -t updates < <(checkupdates && yay -Qum)
    for i in "${updates[@]}"; do
        notify-send "$(echo "$i" | sed 's/\s.*$//')"
    done
fi

updates_arch=$(checkupdates 2> /dev/null | wc -l ) || updates_arch=0
updates_aur=$(yay -Qum 2> /dev/null | wc -l) || updates_aur=0

updates=$(($updates_arch + $updates_aur))

if [ "$updates" -gt 0 ]; then
    echo "$updates"
else
    echo "0"
fi
