#!/bin/bash
# Script should only be run once after cloning the dotfiles

# Check if a package is installed
checkPkg(){
    pacman -Q $1 &>/dev/null || sudo pacman -S $1 --needed --noconfirm
}
# Install yay if needed
yay_check(){
if ! pacman -Qi yay &>/dev/null; then
    git clone https://aur.archlinux.org/yay.git ~/yay
    cd ~/yay
    makepkg -si --noconfirm
    rm -rf ~/yay
fi
}
# Move keyboard layout
keyboard(){
    sudo ln -s  ~/dotfiles/keymaps/colemak /usr/share/X11/xkb/symbols/colemak
}
# Start up and enable onedrive
one_drive(){
    onedrive --synchronize --resync
    systemctl --user enable onedrive
    systemctl --user start onedrive
}
# Stow our config
stow_config(){
    stow x/
    stow bash/
    stow .config/ -t ~/.config/
    stow .local/ -t ~/.local/
}



checkPkg git && yay_check
checkPkg stow && stow_config
paccy --install # Installs all the packages in the .pkgList
keyboard
one_drive
