#!/bin/sh
# MIGHT NOT BE WORKING
# Script should only be run once after cloning the dotfiles

# Check if a package is installed
checkPkg(){
    pacman -Q $1 &>/dev/null || sudo pacman -S $1 --needed --noconfirm
}
# Install yay if needed
yay_check(){
if ! pacman -Qi yay 1>/dev/null; then
    git clone https://aur.archlinux.org/yay.git ~/yay
    cd ~/yay || exit
    makepkg -si --noconfirm
    cd ~/dotfiles || exit
    rm -rf ~/yay
fi
}
# Move keyboard layout
keyboard(){
    sudo ln -s  ~/dotfiles/keymaps/colemak /usr/share/X11/xkb/symbols/colemak
}
dash_install(){
    sudo ln -sfT dash /usr/bin/sh
}
zsh_install(){
    sh -c "$(wget -O- https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    cp  myTheme.zsh-theme ~/.oh-my-zsh/themes/
    chsh -s /bin/zsh
}
# Start up and enable onedrive
one_drive(){
    onedrive --synchronize --resync
    systemctl --user enable onedrive
    systemctl --user start onedrive
}
# Stow our config
stow_config(){
    rm -f ~/.xinitrc ~/.bash_profile ~/.bashrc ~/.config/gtk3-0/settings.ini
    stow x/
    stow bash/
    stow .config/ -t ~/.config/
    stow .local/ -t ~/.local/
    chmod +x ~/dotfiles/.local/bin/*
}

checkPkg git && yay_check
checkPkg stow && stow_config
checkPkg dash && dash_install # Bash is bloated
checkPkg zsh && zsh_install
cp .gitconfig ~/
yay -S --needed $(cut -d ' ' -f1 .pkgList) # Installs all the packages in the .pkgList
keyboard
one_drive
