#!/bin/bash
set -xeuo pipefail

minimal_config() {
  ln -sf $PWD/.local/bin/ ~/.local/

  for f in $PWD/.config/*; do
    ln -sf "$f" ~/.config/
  done

  for f in $PWD/shell/.[!.]*; do
    ln -sf "$f" ~
  done
}

general_config() {
  ln -sf $PWD/.gitconfig ~/

  # Export new path so we get access to everything in bin
  export PATH="$PATH:$PWD/.local/bin"

  # Return if we are running in WSL
  ~/.local/bin/iswsl && return

  sudo mkdir -p -m 755 \
    /etc/systemd/sleep.conf.d/ \
    /etc/systemd/logind.conf.d/ \
    /etc/systemd/resolved.conf.d/

  # Configure sleeping stuff (check this stuff with systemd-analyze cat-config)
  sudo ln -sf $PWD/misc/99-sleep.conf /etc/systemd/sleep.conf.d/
  sudo ln -sf $PWD/misc/99-logind.conf /etc/systemd/logind.conf.d/

  # Keymap
  sudo ln -sf $PWD/keymaps/colemak /usr/share/X11/xkb/symbols/colemak
}

arch_config() {
  [ ! -x "$(command -v pacman)" ] && return

  sudo pacman -S dash --noconfirm --needed

  # Pacman setup
  sudo sed -i '/Color/s/^#//g' /etc/pacman.conf
  # sudo sed -i '/VerbosePkgLists/s/^#//g' /etc/pacman.conf

  sudo ln -sf $PWD/hooks /etc/pacman.d/

  # Since dash is faster than bash
  sudo ln -sfT dash /usr/bin/sh
}

# Cache keys
ssh_agent() {
  mkdir ~/.ssh/
  echo "AddKeysToAgent yes" >>~/.ssh/config
  ln -sf "$(pwd)"/misc/.pam_environment ~/
  systemctl --user enable ssh-agent
  systemctl --user start ssh-agent
}

# Get rid of the stupid KDE wallet thing
kde() {
  kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'Enabled' 'false'
  kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'First Use' 'false'
}

main() {
  minimal_config
  arch_config
  general_config
  arch_dep
  ! ~/.local/bin/iswsl && ssh_agent
}

minimal_config
general_config

