#!/bin/sh
# NOT EVEN CLOSE TO BE WORKING
# Missing: stow not working, onedrive no, etc etc, create trashpath
# Script should only be run once after cloning the dotfiles

# Check if a package is installed
checkPkg(){
    pacman -Q $1 &>/dev/null || sudo pacman -S $1 --needed --noconfirm
}
# Install yay if needed
yay_check(){
if ! pacman -Qi yay 1>/dev/null; then
    git clone https://aur.archlinux.org/yay.git ~/yay
    cd ~/yay || exit
    makepkg -si --noconfirm
    cd ~/dotfiles || exit
    rm -rf ~/yay
fi
}
# Move keyboard layout
keyboard(){
    sudo ln -s  ~/dotfiles/keymaps/colemak /usr/share/X11/xkb/symbols/colemak
}
trash(){
    mkdir -p ~/.local/share/Trash/files
}
dash_install(){
    sudo ln -sfT dash /usr/bin/sh
}
# Start up and enable onedrive
one_drive(){
    onedrive --synchronize --resync
    systemctl --user enable onedrive
    systemctl --user start onedrive
}
# Stow our config
stow_config(){
    rm -f ~/.xinitrc ~/.bash_profile ~/.bashrc ~/.config/gtk3-0/settings.ini
    stow x/
    stow bash/
    stow .config/ -t ~/.config/
    stow .local/ -t ~/.local/
    chmod +x ~/dotfiles/.local/bin/*
}

checkPkg git && yay_check
checkPkg stow && stow_config
checkPkg dash && dash_install # Bash is bloated
trash # Setup trash path
yay -S --needed $(cut -d ' ' -f1 .pkgList) # Installs all the packages in the .pkgList
keyboard
one_drive
