#!/bin/sh

for arg in "$@"; do
    if [ -f "$arg" ] ; then
        case "$arg" in
            *.tar.bz2)   tar xvjf "$arg"    ;;
            *.tar.gz)    tar xvzf "$arg"    ;;
            *.bz2)       bunzip2 "$arg"     ;;
            *.rar)       unrar x "$arg"     ;;
            *.gz)        gunzip "$arg"      ;;
            *.tar)       tar xvf "$arg"     ;;
            *.tbz2)      tar xvjf "$arg"    ;;
            *.tgz)       tar xvzf "$arg"    ;;
            *.zip)       unzip "$arg"       ;;
            *.Z)         uncompress "$arg"  ;;
            *.7z)        7z x "$arg"        ;;
            *)           echo "I don't know how to extract "$arg"..." ;;
        esac
    else
        echo "'$1' is not a valid file!"
    fi
done

