#!/bin/bash
# Pacman + yay wrapper to keep track of installed packages

pkgList=~/dotfiles/.pkgList
install_pkgs(){
    yay -S --needed "$@" || return 1

    # Write the packages to the pkgList
    for pkg in "${@}"; do
        sed -i '/'"$pkg"'/d' "$pkgList" # In case it already exists

        if [ -z "$comment" ]; then
            echo "$pkg" >> "$pkgList"
        else
            echo "$pkg # $comment" >> "$pkgList"
        fi
    done

    # Sort and remove dupes
    local sorted=$(cat "$pkgList" | sort -u)
    echo "$sorted" > "$pkgList"
}
remove_pkgs(){
    sudo pacman -Rns "$@" || return 1
    for pkg in "$@"; do
        sed -i '/'"$pkg"'/d' "$pkgList" 
    done
}
# Installs all the packages listed under the packagelist
install(){
    yay -S --needed --noconfirm $(cut -d ' ' -f1 $pkgList)
}

parameters="$@" # Save the original parameters
pkgInstall=false
pkgRemove=false

while [[ $# -gt 0 ]]; do
    par="$1"
    case $par in
        -Syu) yay -Syu; shift;;
        -S) pkgInstall=true;  shift;;
        -Rns) pkgRemove=true; shift;;
        -c|-C) comment="$2"; shift 2;;
        --install) install; shift;;
        -*) pacman $parameters; exit;; # Pass on to pacman and exit
        *) pkgs+=($par); shift;; # If no dash we'll assume this is a package
    esac
done

$pkgInstall && $pkgRemove && \
echo "You can't both install and remove packages at the same time!" \
&& exit 1

echo "install is $pkgInstall and remove is $pkgRemove"
# Either install or remove pkgs but not both
($pkgInstall && install_pkgs "${pkgs[@]}") || \
($pkgRemove && remove_pkgs "${pkgs[@]}")

