#!/bin/sh
# Requires xclip!
main(){
    isDir=false
    file="$@"

    # Check for text argument
    if [ "$1" = "--text" ]; then
        clbin
        exit
    fi

    # zip files or directory
    if [ "$#" -gt 1 ] || [ -d "$file" ] ; then
        zip -FSr archive.zip "$@" >/dev/null
        file=archive.zip 
        isDir=true
    fi

    notify-send "Upload started"
    # Use boring.host for images and anonfile otherwise
    case "${file#*.}" in
        jpg|jpeg|png|gif)
            boring;;
        *)
            anon;;
    esac

    # Shorten the url
    shorten "$url"
    notify-send "Link copied to clipboard!"

    # Remove archize.zip if directory
    $isDir && rm -rf "$file"
}
shorten(){
    curl -sF 'shorten='"$1" http://0x0.st | xclip -selection clipboard
}
boring(){
    url=$(curl -sF file=@"$file" https://api.boring.host/api/upload | python3 -c \
        "import sys, json; print(json.load(sys.stdin)['data']['direct_url'])")
}
clbin(){
    url=$(xclip -o | curl -sF 'clbin=<-' https://clbin.com)
    notify-send "Text uploaded"
    shorten "$url"
}
anon(){
    url=$(curl -sF file=@"$file" https://anonfile.com/api/upload | python3 -c "import sys, json; print(json.load(sys.stdin)['data']['file']['url']['full'])")
}
# Backup in case anon stops working
file(){
    url=$(curl -sF file=@"$file" https://file.io/ | python3 -c "import sys, json; print(json.load(sys.stdin)['link'])")
}
main "$@"
