#!/bin/sh

# Set environtment variables
export PATH="$PATH:$HOME/go/bin:$(command du "$HOME/.local/bin/" | cut -f2 | paste -sd':')"


# Default programs
export TERMINAL="st"
export TERM="st-256color"
export EDITOR="nvim"
export VISUAL="nvim"
export BROWSER="brave"
export FILE="pcmanfm"

# XDG
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"

# Program settings
export FZF_DEFAULT_COMMAND="rg --files --hidden"
export FZF_LEGACY_KEYBINDINGS="0" # disable legacy keybindings
export SUDO_ASKPASS="dmenupass"
export _JAVA_AWT_WM_NONREPARENTING="1"
export DOCKER_BUILDKIT=1

# Clean up ~/
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export LESSHISTFILE="-"
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc


[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx >>/tmp/xLog 2>&1
# Load aliases
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"
