#!/bin/sh

# Set environtment variables
export PATH="$PATH:$HOME/go/bin:$(du "$HOME/.local/bin/" | cut -f2 | paste -sd':')"

export TERM="xterm-256color"

# Default programs
export TERMINAL="st"
export EDITOR="nvim"
export VISUAL="nvim"
export BROWSER="brave"

# XDG
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"

# Program settings
export FZF_DEFAULT_COMMAND="rg --files --hidden"
export FZF_LEGACY_KEYBINDINGS="0" # disable legacy keybindings
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export _JAVA_AWT_WM_NONREPARENTING="1"

# Clean up ~/
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export LESSHISTFILE="-"
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export PYLINTHOME="$XDG_CACHE_HOME"/pylint
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && shortcuts >/dev/null 2>&1 &

[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx
