# vim-like seeking
k seek -5
i seek 5
#n seek -60
#e seek 60

# Cycle between subtitle files
n cycle sub down
e cycle sub

F5         no-osd screenshot

# Anime profile
Ctrl+a     apply-profile "anime" ; show-text "Profile: anime" 1500
