#!/bin/bash

cmd="$1"
path="$(tmux display -p '#{pane_current_path}')"

# Generate session name based on cmd or "shell" if empty
session_type="${cmd:-shell}"
session="$(tmux display -p "_${session_type}_#S")"

if ! tmux has -t "=$session" 2>/dev/null; then
  parent_session="$(tmux display -p '#{session_id}')"

  if [ -z "$cmd" ]; then
    session_id="$(tmux new-session -c "$path" -dP -s "$session" -F '#{session_id}' -e TMUX_PARENT_SESSION="$parent_session")"
  else
    session_id="$(tmux new-session -c "$path" -dP -s "$session" -F '#{session_id}' -e TMUX_PARENT_SESSION="$parent_session" -- "$cmd")"
  fi

  tmux set-option -s -t "$session_id" key-table popup
  tmux set-option -s -t "$session_id" status off
  session="$session_id"
fi

exec tmux attach -t "=$session" -c "$path" >/dev/null
