#!/usr/bin/env bash

cmd="$1"
path="$(tmux display -p '#{pane_current_path}')"
parent_session_name="$(tmux display -p '#S')"

# Generate session name based on cmd or "shell" if empty
session_type="${cmd:-shell}"
session="_${session_type}_${parent_session_name}"

if ! tmux has -t "=$session" 2>/dev/null; then
  parent_session="$(tmux display -p '#{session_id}')"

  if [ -z "$cmd" ]; then
    session_id="$(tmux new-session -c "$path" -dP -s "$session" -F '#{session_id}' -e TMUX_PARENT_SESSION="$parent_session")"
  else
    session_id="$(tmux new-session -c "$path" -dP -s "$session" -F '#{session_id}' -e TMUX_PARENT_SESSION="$parent_session" -- "$cmd")"
  fi

  tmux set-option -s -t "$session_id" key-table popup
  tmux set-option -s -t "$session_id" status off
  tmux set-option -s -t "$session_id" prefix None
  tmux set-option -t "$session_id" @tmux_go_private_session 1
  tmux set-option -t "$session_id" @tmux_go_parent_session "$parent_session_name"
  session="$session_id"
fi

exec tmux attach -t "=$session" -c "$path" >/dev/null
