#!/usr/bin/env bash

term="alacritty"

riverctl map normal Super Return spawn "$term"

riverctl map normal Super Q close                                         # Close window
riverctl map normal Super+Shift Q exit                                    # Exit river
riverctl map normal Super N focus-view next                               # Next window
riverctl map normal Super E focus-view previous                           # Previous window
riverctl map normal Super+Shift N swap next                               # Swap to next Window
riverctl map normal Super+Shift E swap previous                           # Swap to previous Window
riverctl map normal Super Period focus-output next                        # Next output
riverctl map normal Super Comma focus-output previous                     # Previous output
riverctl map normal Super+Shift Period send-to-output next                # Send window to next output
riverctl map normal Super+Shift Comma send-to-output previous             # Send window to previous output
riverctl map normal Super+Shift Return zoom                               # Move window to top of stack
riverctl map normal Super Space toggle-float                              # Toggle float
riverctl map normal Super F toggle-fullscreen                             # Toggle full screen
riverctl map normal Super Print spawn 'grim -g "$(slurp -d)" - | wl-copy' # Screenshot
riverctl map-pointer normal Super BTN_LEFT move-view                      # Move window
riverctl map-pointer normal Super BTN_RIGHT resize-view                   # Resize window
riverctl map-pointer normal Super BTN_MIDDLE toggle-float                 # Toggle floating

riverctl map normal Super M send-layout-cmd rivertile "main-ratio -0.05"    # Decrease main ratio
riverctl map normal Super I send-layout-cmd rivertile "main-ratio +0.05"    # Increase main ratio
riverctl map normal Super+Shift M send-layout-cmd rivertile "main-count -1" # Increase main count
riverctl map normal Super+Shift I send-layout-cmd rivertile "main-count +1" # Decrease main count

riverctl send-layout-cmd rivertile "view-padding 1"

# Programs
riverctl map normal Super D spawn "fuzzel -I -T $term"
riverctl map normal Super V spawn brave

# Super+Alt+{M,N,E,I} to move views
riverctl map normal Super+Alt M move left 100
riverctl map normal Super+Alt N move down 100
riverctl map normal Super+Alt E move up 100
riverctl map normal Super+Alt I move right 100

# Super+Alt+Control+{M,N,E,I} to snap views to screen edges
riverctl map normal Super+Alt+Control M snap left
riverctl map normal Super+Alt+Control N snap down
riverctl map normal Super+Alt+Control E snap up
riverctl map normal Super+Alt+Control I snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift M resize horizontal -100
riverctl map normal Super+Alt+Shift N resize vertical -100
riverctl map normal Super+Alt+Shift E resize vertical 100
riverctl map normal Super+Alt+Shift I resize horizontal 100

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested Wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
  # Eject the optical drive (well if you still have one that is)
  riverctl map $mode None XF86Eject spawn 'eject -T'

  # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
  riverctl map $mode None XF86AudioRaiseVolume spawn 'amixer -q sset Master 5%+'
  riverctl map $mode None XF86AudioLowerVolume spawn 'amixer -q sset Master 5%-'
  riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  # riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  # riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  # riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  # riverctl map $mode None XF86AudioNext spawn 'playerctl next'

  riverctl map $mode None XF86MonBrightnessUp spawn 'lightcontrol -d +500'
  riverctl map $mode None XF86MonBrightnessDown spawn 'lightcontrol -d -500'
  riverctl map $mode Shift XF86MonBrightnessUp spawn 'lightcontrol -d +100'
  riverctl map $mode Shift XF86MonBrightnessDown spawn 'lightcontrol -d -100'
done

# Set background and border color
riverctl background-color 0xb5b5b5
riverctl border-color-focused 0x0x666666
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
# https://git.sr.ht/~leon_plickat/lswt
riverctl rule-add -app-id 'imv' float
riverctl rule-add -app-id 'mpv' float
riverctl rule-add -app-id 'nz.co.mega.megasync' float
riverctl rule-add -app-id 'gnome-system-monitor' float
riverctl rule-add -app-id 'xdg-desktop-portal-gtk' float # file chooser

# Make all views with app-id "bar" and any title use client-side decorations
# riverctl rule-add csd -app-id "bar"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile

riverctl spawn "rivertile -outer-padding 0 -view-padding 0"
riverctl output-layout rivertile

# riverctl keyboard-layout colemak

for i in {1..9}; do
  tags=$((1 << (i - 1)))

  # Super+[1-9] to focus tag [0-8]
  riverctl map normal Super "$i" set-focused-tags $tags

  # Super+Shift+[1-9] to tag focused view with tag [0-8]
  riverctl map normal Super+Shift "$i" set-view-tags $tags

  # Super+Control+[1-9] to toggle focus of tag [0-8]
  riverctl map normal Super+Control "$i" toggle-focused-tags $tags

  # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
  riverctl map normal Super+Shift+Control "$i" toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Configuration
riverctl focus-follows-cursor always
riverctl hide-cursor timeout 15000
riverctl hide-cursor when-typing disabled

# Input configuration (riverctl list-inputs)
touchpad="pointer-1267-12693-ELAN0676:00_04F3:3195_Touchpad"
riverctl input "$touchpad" click-method clickfinger
riverctl input "$touchpad" disable-while-typing enabled
riverctl input "$touchpad" middle-emulation enabled
riverctl input "$touchpad" tap enabled
riverctl input "$touchpad" tap-button-map left-right-middle
riverctl input "$touchpad" scroll-method two-finger

riverctl input "pointer-1390-316-ELECOM_OpticalMouse" accel-profile none
riverctl input "pointer-1390-316-ELECOM_OpticalMouse" pointer-accel -0.3

# WAYLAND_DISPLAY XDG_CURRENT_DESKTOP needs to be set for xdg-desktop-portal-wlr to work
# https://wiki.archlinux.org/title/XDG_Desktop_Portal
riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"

riverctl spawn "swaybg -i ~/.config/pape/bg.png"
riverctl spawn "gammastep -t 6500K:2500K -l $LAT_LON"
riverctl spawn "dunst"
riverctl spawn "fcitx5"
