#!/bin/bash

term="alacritty"

riverctl map normal Super Return spawn "$term"

riverctl map normal Super Q close                             # Close window
riverctl map normal Super+Shift Q exit                        # Exit river
riverctl map normal Super N focus-view next                   # Next window
riverctl map normal Super E focus-view previous               # Previous window
riverctl map normal Super+Shift N swap next                   # Swap to next Window
riverctl map normal Super+Shift E swap previous               # Swap to previous Window
riverctl map normal Super Period focus-output next            # Next output
riverctl map normal Super Comma focus-output previous         # Previous output
riverctl map normal Super+Shift Period send-to-output next    # Send window to next output
riverctl map normal Super+Shift Comma send-to-output previous # Send window to previous output
riverctl map normal Super+Shift Return zoom                   # Move window to top of stack
riverctl map normal Super Space toggle-float                  # Toggle float
riverctl map normal Super F toggle-fullscreen                 # Toggle full screen
riverctl map-pointer normal Super BTN_LEFT move-view          # Move window
riverctl map-pointer normal Super BTN_RIGHT resize-view       # Resize window
riverctl map-pointer normal Super BTN_MIDDLE toggle-float     # Toggle floating

riverctl map normal Super M send-layout-cmd rivertile "main-ratio -0.05"    # Decrease main ratio
riverctl map normal Super I send-layout-cmd rivertile "main-ratio +0.05"    # Increase main ratio
riverctl map normal Super+Shift M send-layout-cmd rivertile "main-count -1" # Increase main count
riverctl map normal Super+Shift I send-layout-cmd rivertile "main-count +1" # Decrease main count

# Programs
riverctl map normal Super D spawn "fuzzel -I -T $term"

# Super+Alt+{M,N,E,I} to move views
riverctl map normal Super+Alt M move left 100
riverctl map normal Super+Alt N move down 100
riverctl map normal Super+Alt E move up 100
riverctl map normal Super+Alt I move right 100

# Super+Alt+Control+{M,N,E,I} to snap views to screen edges
riverctl map normal Super+Alt+Control M snap left
riverctl map normal Super+Alt+Control N snap down
riverctl map normal Super+Alt+Control E snap up
riverctl map normal Super+Alt+Control I snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift M resize horizontal -100
riverctl map normal Super+Alt+Shift N resize vertical -100
riverctl map normal Super+Alt+Shift E resize vertical 100
riverctl map normal Super+Alt+Shift I resize horizontal 100

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested Wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
  # Eject the optical drive (well if you still have one that is)
  riverctl map $mode None XF86Eject spawn 'eject -T'

  # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
  riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5'
  riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5'
  riverctl map $mode None XF86AudioMute spawn 'pamixer --toggle-mute'

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  # riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  # riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  # riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  # riverctl map $mode None XF86AudioNext spawn 'playerctl next'

  riverctl map $mode None XF86MonBrightnessUp spawn 'lightcontrol -d +10'
  riverctl map $mode None XF86MonBrightnessDown spawn 'lightcontrol -d -10'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x4dcc8e
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl float-filter-add app-id 'MEGAsync'
riverctl float-filter-add app-id 'gnome-system-monitor'

# Make all views with app-id "bar" and any title use client-side decorations
# riverctl rule-add csd -app-id "bar"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

riverctl spawn rivertile
riverctl output-layout rivertile

riverctl keyboard-layout colemak

for i in {1..9}; do
  tags=$((1 << (i - 1)))

  # Super+[1-9] to focus tag [0-8]
  riverctl map normal Super "$i" set-focused-tags $tags

  # Super+Shift+[1-9] to tag focused view with tag [0-8]
  riverctl map normal Super+Shift "$i" set-view-tags $tags

  # Super+Control+[1-9] to toggle focus of tag [0-8]
  riverctl map normal Super+Control "$i" toggle-focused-tags $tags

  # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
  riverctl map normal Super+Shift+Control "$i" toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Configuration
riverctl focus-follows-cursor normal
riverctl hide-cursor timeout 3000
riverctl hide-cursor when-typing disabled

# Input configuration
touchpad="pointer-1102-4620-ALP000D:00_044E:120C"
riverctl input "$touchpad" click-method clickfinger
riverctl input "$touchpad" disable-while-typing enabled
riverctl input "$touchpad" middle-emulation enabled
riverctl input "$touchpad" tap enabled
riverctl input "$touchpad" tap-button-map left-right-middle
riverctl input "$touchpad" scroll-method two-finger

riverctl spawn "swaybg -o eDP-1 -i ~/sync/Wallpapers/81g4h40e2c471.jpg"
riverctl spawn "pipewire"
riverctl spawn "wireplumber"
riverctl spawn "pipewire-pulse"

