# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
keybinding:
  universal:
    return: 'q' # return to previous menu, will quit if there's nowhere to return
    edit: 'o'
    prevItem: 'e' # go one line up
    nextItem: 'n' # go one line down
    prevItem-alt: '<up>' # go one line up
    nextItem-alt: '<down>' # go one line down

    prevBlock: 'm' # go to the previous block / panel
    nextBlock: 'i' # go to the next block / panel

    scrollUpMain: 'E' # main panel scroll up
    scrollDownMain: 'N' # main panel scroll down
    scrollUpMain-alt1: '<pgup>' # main panel scroll up
    scrollDownMain-alt1: '<pgdown>' # main panel scroll down

    scrollLeft: 'M' # scroll left within list view
    scrollRight: 'I' # scroll right within list view
    nextMatch: 'l'
    prevMatch: 'L'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  showFileTree: false
  showCommandLog: false
