settings:
  separator: " / "
  write_to_stdout: true
blocks:
  - command: getconn
    interval: 60s
    icon: " "

  - command: gettraffic
    interval: 10s

  - command: getupdates
    interval: 1h
    icon: " "

  - command: getvol
    update_signals: [51]

  - command: sh
    icon: " "
    update_signals: [50]
    args: [-c, "lightcontrol -c"]

  - command: sh
    icon: " "
    interval: 10s
    args:
      - -c
      - top -bn1 | awk '/Cpu\(s\)/ {printf "%.2f%%\n", 100 - $8}'

  - command: sh
    icon: " "
    interval: 10s
    args:
      - -c
      - free --bytes | awk '/Mem/ {printf "%.2f%\n", $3/$2 * 100.0}'

  - command: getbat
    enabled: "[[ -d /sys/class/power_supply/BAT0 ]]"
    interval: 120s

  - command: getdate
    interval: 1h
    icon: " "

  - command: gettime
    interval: 30s
    icon: " "
