# See /etc/systemd/logind.conf for defaults.
# See logind.conf(5) for details.

[Login]
HandleLidSwitch=suspend-then-hibernate
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore

IdleAction=suspend-then-hibernate
IdleActionSec=3min

HandleSuspendKey=suspend-then-hibernate
