#!/bin/bash

pidof dunst && killall dunst
dunst &

dunstify -u low "low" "This is not a very urgent message"
dunstify -u normal "normal" "This is a normal message."
dunstify -u critical "critical" "This is a very critical message!"
