#!/bin/bash
xrdb -load ~/.Xresources &
dunst &
compton -b &
redshift &
feh --randomize --bg-fill ~/OneDrive/Wallpapers/3440x1440/ &
xset r rate 210 30 &
~/.scripts/administrative/entr &
nm-applet &
fcitx &
~/.config/polybar/launch.sh &
