# name: Devenv Docker Image CI
#
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - master
#
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Build the Docker image
#         run: |
#           echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin docker.io
#           docker build . --tag docker.io/${{ secrets.DOCKER_HUB_USER }}/dev:latest
#           docker push docker.io/${{ secrets.DOCKER_HUB_USER }}/dev:latest
