name: Linter

on:
  - workflow_dispatch
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      - name: Lint shell
        run: ./bin/task -v c:lint:shell
