name: Linter

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: sudo snap install shfmt shellcheck
      - uses: actions/checkout@v2
      - name: Lint shell scripts
        run: while read -r f; do echo "checking $f"; shellcheck "$f"; done < <(shfmt -f .)
